spring:
  application:
    name: xumblaubs-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/xumblaubs_rentcar
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    defer-datasource-initialization: true
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890123456789012345678901234567890abcdefghijklmnop
      expiration: 86400000 # 24 hours

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    com.xumblaubs: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
