spring:
  application:
    name: sismop-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/xumblaubs_rentcar
    username: postgres
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        hbm2ddl:
          auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false
      separator: ;
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.sismop: DEBUG
    org.springframework.security: DEBUG
